### ISSUE TITLE
[Bug]: Jellyfin

### ISSUE THREAD

**Issue by MisterSuki** [Ashu11-A/Ashu_eggs#10]
### Panel Version

1.11.7

### Wings Version

1.11

### Service

Jellyfin

### Modified

No, I did not modify the egg

### Expected Behavior

when I launch the server it gives me this

[Pterodactyl Daemon]: Finished pulling Docker container image:/home/container$ bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/Jellyfin/install.sh)mkdir: cannot create directory '/mnt/server': Read-only file system/dev/fd/63: line 7: cd: /mnt/server: No such file or directorycontainer@pterodactyl~ Server marked as offline...
![Capture d’écran 2024-06-19 161530](https://github.com/Ashu11-A/Ashu_eggs/assets/80472119/6bad7716-9bfa-4348-8f9c-efa2842f3eca)

### Actual Behavior

when the installation is done it gives me this error in the console
![Capture d’écran 2024-06-19 161555](https://github.com/Ashu11-A/Ashu_eggs/assets/80472119/f4c34a67-868f-4ce1-8d60-66465be103d4)

### Steps To Reproduce

the version of the eggs I just downloaded it so I don't know where the problem comes from

Running hooks in /etc/ca-certificates/update.d...
done.
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'jellyfin_10.8.5/*': No such file or directory
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from ashu11a/jellyfin 
Status: Image is up to date for ashu11a/jellyfin:latest 
Digest: sha256:8bd08f1cfad928d23a6a07522f8a081c2e9ba69b775ddeaca8f19537f0393986 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/Jellyfin/install.sh)
mkdir: cannot create directory '/mnt/server': Read-only file system
/dev/fd/63: line 7: cd: /mnt/server: No such file or directory
container@pterodactyl~ Server marked as offline...
![Capture d’écran 2024-06-19 161458](https://github.com/Ashu11-A/Ashu_eggs/assets/80472119/2f901033-2425-43ab-8078-48eb165439c6)

### Install logs

bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/Jellyfin/install.sh)

**Comment by Ashu11-A** [comment]
I'll check it out

**Comment by Ashu11-A** [comment]
They've changed the location of the download files, I'll be fixing it

**Comment by Ashu11-A** [comment]
Working!
You must update the Egg, the docker URL has changed, so any existing servers must be changed manually, or deleted and recreated

Give it a try, because I'm having a problem with the port, it's not being changed, if it doesn't work, I'll have to implement a reverse proxy with nginx
![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/79a5dc38-8a48-4705-b198-7f0f4383ea21)

**Comment by Ashu11-A** [comment]
![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/ac8ab77a-c463-476b-8400-a22e805996c8)

**Comment by MisterSuki** [comment]
Okay I'm going to change all of that and I'll keep you posted
