### ISSUE TITLE
[Egg Request]: what happened to the webserver egg?

### ISSUE THREAD

**Issue by xxcomcadxx** [Ashu11-A/Ashu_eggs#12]
### Does this expand an already existing service

Yes

### Link to a game or software

/

### Links for the download

/

### Links for the install docs

/

### Does this app work on ARM?

No

**Comment by Ashu11-A** [comment]
I think you're wrong, I don't distribute this Egg.
Take a look at this link: https://github.com/Sigma-Production/ptero-eggs
