### ISSUE TITLE
[Bug]: Unable to start Jellyfin

### ISSUE THREAD

**Issue by WinterPlays123** [Ashu11-A/Ashu_eggs#3]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

Jellyfin

### Modified

No, I did not modify the egg

### Expected Behavior

Install server
Start server
Server starts correctly.

### Actual Behavior

Error:
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from ashu11a/jellyfin 
Status: Image is up to date for ashu11a/jellyfin:latest 
Digest: sha256:8bd08f1cfad928d23a6a07522f8a081c2e9ba69b775ddeaca8f19537f0393986 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Jellyfin/install.sh)
/dev/fd/63: line 1: 404:: command not found
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false

### Steps To Reproduce

Start server

### Install logs

https://pteropaste.com/m2w6va280lv6

**Comment by Ashu11-A** [comment]
Hello, I moved the folders, which broke everything, update Egg, sorry for the inconvenience
