### ISSUE TITLE
[Bug]: VPS egg bug +yt-dl error

### ISSUE THREAD

**Issue by jacksonm36** [Ashu11-A/Ashu_eggs#4]
### Panel Version

Jexactyl 3.7.2

### Wings Version

1.11.7

### Service

VPS-egg+egg-youtube-dl-web

### Modified

No, I did not modify the egg

### Expected Behavior

install-configure the vps-server egg then start it 

### Actual Behavior

server crashed with the following error both with debian-alpine.

1.
Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/vps/selector.sh)
/dev/fd/63: line 1: 404:: command not found
Jexactyl: Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false

2. narrowing it down when i open the https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/vps/selector.sh) link 404 error appears in a normal browser 

3.the yt-dl egg has a similliar error  
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from ashu11-a/software 
Status: Image is up to date for ghcr.io/ashu11-a/software:youtube_dl 
Digest: sha256:bd5c4a3fa9b1107740c27c6c8d191cf786c97060ca73698fed4a180e9d05b0b0 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./start.sh
./start.sh: line 1: 404:: command not found
Jexactyl: Server marked as offline...

### Steps To Reproduce

1. install the server from the egg-vps.json
2. select version tried with alpine-debian 
3. what the f? 

### Install logs

https://pteropaste.com/b1n1iwnb3kz7/

**Comment by Ashu11-A** [comment]
The English version of this egg was not made, use pt-BR

**Comment by jacksonm36** [comment]
> The English version of this egg was not made, use pt-BR

yeah it works with it but i cant understand jack sh1t
