### ISSUE TITLE
[Bug]: Error Emby

### ISSUE THREAD

**Issue by NikitoDev** [Ashu11-A/Ashu_eggs#6]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Emby Egg

### Modified

No, I did not modify the egg

### Expected Behavior

![image](https://github.com/Ashu11-A/Ashu_eggs/assets/100253627/5c24363a-e48b-4795-b505-c020bc87bd06)

### Actual Behavior

:/home/container$ bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/Emby/install.sh)
⚙️ Script Version: 1.4
✅ Starting Emby
You must install or update .NET to run this application.
App: /home/container/Emby/EmbyServer.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  6.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=ubuntu.22.04-x64

### Steps To Reproduce

1. Install
2. Start
3. Error X

### Install logs

https://pteropaste.com/fh24uhtyfacv

**Comment by Ashu11-A** [comment]
Isso realmente está funcionando?

**Comment by Ashu11-A** [comment]
Emby's server isn't working because they've changed the dotnet version from 6 to 8. I'll fix it.

**Comment by Ashu11-A** [comment]
# Please update Egg to version 2.1

### Commits:
#### Updated Docker:
- [#accc47d](https://github.com/Ashu11-A/Ashu_Yolks/commit/accc47d50e05ee2b2fa80b95d4a1868ac8bbd2a2)
- [#95b245a](https://github.com/Ashu11-A/Ashu_Yolks/commit/95b245aec38f1835329b352f1fc23028ef2a1aaf)
- [#6bee5c3](https://github.com/Ashu11-A/Ashu_Yolks/commit/6bee5c3ec9f9423a32ce9e361630604b55c9b972)

### Update Egg:
- [#e7a3f59](https://github.com/Ashu11-A/Ashu_eggs/commit/e7a3f594e61217a15bdf86f20b8901d7a9733898)

| |
|--|
|  ![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/c39cb981-78af-4ae3-8bdb-022ed4361c24)
| ![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/823a0282-16a2-4e84-b315-0a092093306c)
