### ISSUE TITLE
[Bug]: YT DL Start.sh missing

### ISSUE THREAD

**Issue by Phyroks** [Ashu11-A/Ashu_eggs#8]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

ytdl

### Modified

No, I did not modify the egg

### Expected Behavior

Server will start

### Actual Behavior

start.sh contains 404

### Steps To Reproduce

install server with egg
start the server

### Install logs

https://pteropaste.com/p5b7wrxo84w7/

**Comment by Ashu11-A** [comment]
Not all the scripts have been translated into English, but I'm going to sort them out today. I think I'll create the eggs with the possibility of selecting the language

**Comment by Ashu11-A** [comment]
### Commits:
[#cc41e39](https://github.com/Ashu11-A/Ashu_eggs/commit/cc41e39567c292a06095681ecf4724b9559ba78e)
[#40154c9](https://github.com/Ashu11-A/Ashu_eggs/commit/40154c94db758670e55f7fc486816de096ca45a9)

| | |
|--|--|
| ![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/5fd30f00-c488-4611-b589-f26cca22c8a8) | ![image](https://github.com/Ashu11-A/Ashu_eggs/assets/30575805/bc5c9916-9b9f-44e3-ad79-5f54c38009df)
