### ISSUE TITLE
[Bug]: Error 500 when Importing Tmodloader egg

### ISSUE THREAD

**Issue by SavageTheUnicorn** [Ashu11-A/Ashu_eggs#9]
### Panel Version

1.11.7

### Wings Version

Latest.

### Service

Tmodloader

### Modified

No, I did not modify the egg

### Expected Behavior

Import egg successfully. 

### Actual Behavior

Server Error 500 when Importing. Tried removing the line, "file_denylist: []," but this did not work for me. 

### Steps To Reproduce

Simply just import it into a pterodactyl instance.

### Install logs

Not even necessary.

**Comment by Ashu11-A** [comment]
Egg must be out of date, I'll fix it as soon as possible

**Comment by SavageTheUnicorn** [comment]
That'd be preeeetty cool of you 🫡😂

**Comment by Ashu11-A** [comment]
I didn't find the problem in the Portuguese version, I'll be merging the English version, I've added the Dotnet 8 docker which is now required in the new versions

**Comment by Ashu11-A** [comment]
I didn't find the problem in the Portuguese version, I'll be merging the English version, I've added the Dotnet 8 docker which is now required in the new versions

**Comment by Ashu11-A** [comment]
just a reminder that compatibility with Arm64 has been compromised in the new versions

**Comment by Ashu11-A** [comment]
I've updated Egg, test it, on my machine I'm having a problem with the initialization command:
```sh
bash <(curl -s https://raw.githubusercontent.com/Ashu11-A/Ashu_eggs/main/Connect/en/tModLoader/install.sh)
```
But I was told that it still works, I don't understand what's going on with my panel

**Comment by Ashu11-A** [comment]
No user interactions, closing issue

**Comment by SavageTheUnicorn** [comment]
> just a reminder that compatibility with Arm64 has been compromised in the new versions

This is why I didn't bother updating, my apologies! My server runs arm64 architecture so I cannot test this further than importing the egg, which I'm sure you've solved now!
